name: Release Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        wget https://raw.githubusercontent.com/ivan-hc/VLC-appimage/main/vlc
        chmod a+x vlc
        sudo vlc
        mv /opt/vlc/vlc vlc.AppImage

    - name: Release AppImage
      uses: ncipollo/release-action@v1
      with:
        name: VLC AppImage
        allowUpdates: True
        prerelease: False
        artifacts: "VLC.AppImage*"
        token: $version
        omitNameDuringUpdate: False
        omitBodyDuringUpdate: False
        tag: v$version
        replacesArtifacts: true
