name: Release Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ivan-hc/VLC-appimage
    - name: build
      run: |
        wget https://raw.githubusercontent.com/ivan-hc/VLC-appimage/main/vlc
        chmod a+x ./vlc
        sudo ./vlc
        mv /opt/vlc/vlc vlc-$VERSION-x86_64.AppImage

    - name: Release AppImage
      uses: ivan-hc/VLC-appimage
      with:
        name: VLC AppImage
        allowUpdates: True
        prerelease: False
        artifacts: "vlc-$VERSION-x86_64.AppImage"
        token: $VERSION
        omitNameDuringUpdate: False
        omitBodyDuringUpdate: False
        tag: v$VERSION
        replacesArtifacts: false
