name: Release Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
 	wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
	wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/tools/pkg2appimage
	chmod a+x ./appimagetool ./pkg2appimage
        wget https://raw.githubusercontent.com/ivan-hc/VLC-appimage/main/recipe.yml
	cp ./tmp/recipe.yml ./recipe.yml
	./pkg2appimage ./recipe.yml;
	rm -R -f ./vlc.AppDir/vlc.desktop
	wget https://raw.githubusercontent.com/ivan-hc/VLC-appimage/main/vlc.desktop
	mv vlc.desktop ./vlc.AppDir/vlc.desktop
	rm -R -f ./vlc.AppDir/AppRun
	wget https://raw.githubusercontent.com/ivan-hc/VLC-appimage/main/AppRun
	chmod a+x AppRun
	cp ./AppRun ./
	mv ./AppRun ./vlc.AppDir
	ARCH=x86_64 ./appimagetool -n ./vlc.AppDir
	underscore=_
	mkdir version
	mv ./vlc$underscore*.deb ./version/
	version=$(ls ./tmp/version)
	cd ..;
	mv ./tmp/*.AppImage vlc.AppImage

    - name: Release AppImage
      uses: ncipollo/release-action@v1
      with:
        name: VLC AppImage
        allowUpdates: True
        prerelease: False
        artifacts: "VLC.AppImage*"
        token: $version
        omitNameDuringUpdate: False
        omitBodyDuringUpdate: False
        tag: v$version
        replacesArtifacts: true
